source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '5.1'

target 'BPushSDKExample', :exclusive => true do
    pod "BPushSDK", :path => "../"
end

target 'BPushSDKTests', :exclusive => true do
    pod "BPushSDK", :path => "../"
end